/**
  Create Table Student
 */
CREATE TABLE IF NOT EXISTS STUDENT
(
    ID         UUID DEFAULT RANDOM_UUID() PRIMARY KEY,
    NAME       VARCHAR(100) NOT NULL,
    LAST_NAME  VARCHAR(100) NOT NULL,
    STATE      VARCHAR(20)  NOT NULL,
    AGE        INT          NOT NULL,
    CREATED_AT TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP    NULL
);